In [1]:
import numpy as np

Creation of Numpy Arrays

In [4]:
myList = [1,2,3,4,5]
myArray= np.array([1,2,3,4])

print(myList)
print(myArray)
type(myList)
type(myArray)


[1, 2, 3, 4, 5]
[1 2 3 4]


numpy.ndarray

In [5]:
newArray = np.array(myList)
type(newArray)

numpy.ndarray

In [6]:
##Matrix
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]   #nested list, 2d list
print(myMatrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
np.array(myMatrix)   ##2D numpy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(10)

array([0.07378817, 0.94611042, 0.36817775, 0.4758044 , 0.51286769,
       0.63993531, 0.81616387, 0.98977469, 0.91129029, 0.58279766])

In [18]:
np.random.rand(5,5)

array([[0.96407968, 0.59346498, 0.67552967, 0.96911735, 0.40716405],
       [0.64409185, 0.64160438, 0.30740268, 0.18992557, 0.86651934],
       [0.15906424, 0.41560567, 0.62454324, 0.40100863, 0.20449783],
       [0.53098812, 0.20266536, 0.73032506, 0.59099956, 0.87773439],
       [0.58327164, 0.90965676, 0.44051513, 0.23245636, 0.31206512]])

In [30]:
np.random.randint(1,100,12)

array([70, 93, 94, 15, 53, 71, 26, 34, 30, 33, 77, 12])

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr.max()

45

In [39]:
ranarr.min()

0

In [41]:
ranarr.mean()

23.9

In [42]:
ranarr.argmax()

2

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.reshape(25,1).shape

(25, 1)

In [50]:
arr.dtype

dtype('int32')

In [51]:
arr2 = np.array([1.2,2.3])
arr2.dtype

dtype('float64')

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [60]:
arr[::] = 33
arr

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33])

In [62]:
arr[0:3] = 22
arr 

array([22, 22, 22, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33])

In [63]:
arr_copy = arr.copy()
arr_copy

array([22, 22, 22, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33])

In [64]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
#Indexing 1st row
arr_2d [1][1]

5

In [72]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

4

In [74]:
arr_2d[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [77]:
arr_2d[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [79]:
#Conditions

arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
arr_bool = arr[arr>4]
arr_bool

array([ 5,  6,  7,  8,  9, 10])

In [84]:
arr_bool>4

array([ True,  True,  True,  True,  True,  True])

In [87]:
#Arithematic operations

arr_sum= arr+arr
print(arr_sum)

[ 2  4  6  8 10 12 14 16 18 20]


In [88]:
arr_sum= arr/arr
print(arr_sum)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [89]:
arr_sum= arr%arr
print(arr_sum)

[0 0 0 0 0 0 0 0 0 0]


In [90]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [92]:
np.sqrt(arr)
np.exp(arr)
np.sin(arr)
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [93]:
np.mean(arr)

5.5

In [94]:
arr.mean()

5.5

In [95]:
arr2d= np.array([[1,2,3],[4,5,6],[6,7,8]])

In [96]:
arr2d.sum(axis=0)

array([11, 14, 17])

In [97]:
arr2d.sum(axis=1)

array([ 6, 15, 21])