In [1]:
import numpy as np

Creation of Numpy Arrays

In [4]:
myList = [1,2,3,4,5]
myArray= np.array([1,2,3,4])

print(myList)
print(myArray)
type(myList)
type(myArray)


[1, 2, 3, 4, 5]
[1 2 3 4]


numpy.ndarray

In [5]:
newArray = np.array(myList)
type(newArray)

numpy.ndarray

In [6]:
##Matrix
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]   #nested list, 2d list
print(myMatrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
np.array(myMatrix)   ##2D numpy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])