In [1]:
import numpy as np

In [5]:
#creating array using numpy
#creating a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
#creating a 2d array
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])   #2 rows and 5 columns 
print(arr2)
print(type(arr2))
print(arr2.size)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>
10
(2, 5)


In [11]:
#Converting 1D array to 2D array
arr3= np.array([20,30,40,50])
arr3.reshape(1,4)
print(arr3)
print(type(arr3))
print(arr3.size)
print(arr3.shape)

[20 30 40 50]
<class 'numpy.ndarray'>
4
(4,)


In [15]:
#Creating arrays with inbuilt functions
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
#Print all ones in array
np.ones((3,3))   #inside is a tuple

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#Print all zeros in array
arr4 = np.zeros((3,3))
arr5 = np.zeros((3))

print(arr4)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [23]:
#Identity matrix
np.eye(2,2)   #all diagonals are ones

array([[1., 0.],
       [0., 1.]])

In [38]:
#All details about array:

arr6 = np.array([[1,2,3,4],[5,4,3,6],[5,6,4,3]])
print(arr6)

print(type(arr6))  #type of array
print(arr6.shape)  #shape of array (row,column)
print(arr6.size)
print(arr6.dtype) #datatype of array
print(arr6.ndim)  #number of dimensions (count of length and breadth)
print(arr6.itemsize) #item size of array

[[1 2 3 4]
 [5 4 3 6]
 [5 6 4 3]]
<class 'numpy.ndarray'>
(3, 4)
12
int32
2
4


In [43]:
###Numpy vectorised operations

arr7 = np.array([10,20,30,40,50])
arr8 = np.array([10,20,30,40,50])

print("addition:",  arr7+arr8)
print("subtraction:",  arr7-arr8)
print("multiplication:",  arr7*arr8)
print("division:",  arr7/arr8)
print("mod:",  arr7%arr8)


addition: [ 20  40  60  80 100]
subtraction: [0 0 0 0 0]
multiplication: [ 100  400  900 1600 2500]
division: [1. 1. 1. 1. 1.]
mod: [0 0 0 0 0]


In [49]:
#Universal functions
arr9 = np.array([10,20,30,40,50])

##sqrt
print(np.sqrt(arr9))

##exponential
print(np.exp(arr9))

##sin
print(np.sin(arr9))

##LOG
print(np.log(arr9))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [51]:
##Array slicing and indexing
arr10= np.array([[1,2,3,4,5],[6,7,8,9,3],[1,2,3,4,5]])
print(arr10)

[[1 2 3 4 5]
 [6 7 8 9 3]
 [1 2 3 4 5]]


In [63]:
num = arr10[0][0]
print(num)

arr10[1:,3:]
arr10[0:2,1:3]
arr10[0:2,2:4]

1


array([[3, 4],
       [8, 9]])

In [65]:
##Modify array elements
arr10[0,0] = 100
print(arr10)


[[100   2   3   4   5]
 [  6   7   8   9   3]
 [  1   2   3   4   5]]


In [67]:
##Practical application 

def normalization(data):
    mean = np.mean(data)
    std= np.std(data)

    normalization = (data-mean)/std
    print("normalized data:", normalization)

data = np.array([1,2,3,3,4])
normalization(data)


normalized data: [-1.56892908 -0.58834841  0.39223227  0.39223227  1.37281295]


In [69]:
#Some more statistical operations

def statisticalOperations(data):

    mean = np.mean(data);
    print(mean)
    median = np.median(data);
    print(median)
    std = np.std(data);
    print(std)
    variance = np.var(data);
    print(variance)


data = np.array([1,2,3,4,5])
statisticalOperations(data)

3.0
3.0
1.4142135623730951
2.0


In [74]:
##Logical operations
data = np.array([1,2,3,4,5])
data>5
data[data>4]

data[(data>=3) & (data<=4)]

array([3, 4])